name: shift_handover_challenge
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  intl: any
  equatable: ^2.0.5
  json_annotation: ^4.9.0
  dartz: ^0.10.1
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  freezed: ^2.4.1
  json_serializable: ^6.7.1
  mockito: ^5.4.6

  flutter_lints: ^2.0.0
  bloc_test: ^9.1.7

flutter:
  uses-material-design: true
